name: CI
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - run: pip install pydantic sqlalchemy openai httpx beautifulsoup4 apscheduler pytest black ruff pydantic-settings pytest-cov
      - run: ruff .
      - run: black --check .
      - run: pytest --cov=models --cov-fail-under=85
